#!/usr/bin/bash
# SPDX-FileCopyrightText: 2024-2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-2.0-only
#
# sngfdx-wrapper (formerly abuild-fpbx-installer-iso)
#
# Copyright (C) 2024-2026, Sangoma US Inc.
#
# Shell wrapper around Ansible role to build ISOs.

usage() {
	echo "
Minimal Usage: $0 -i debian_input.iso

Required:
	-i	Path to [i]nput ISO file.

Optional:
	-b	[B]uild version - defaults to yymm.1 eg. 2504.1 (where .1 is the bump.)
	-d	[D]irectory containing additional DEB files (for faster installs.)
	-k	Locked [k]ernel version. Affects PUB, UPG and INT spice (helps DAHDI hardware.)
	-p	Mini input ISO for network installs with [P]XE and Cobbler.
	-o	[O]lder input ISO with DAHDI hardware friendly kernel.
	-w	Do[w]nload FreePBX package files into -d directory (otherwise no network is required.)
	-x	E[x]tract -i input ISO DEBs into -d directory (otherwise existing contents will be used.)

Notes:
	The -w and -x options accept no args themselves,
	but they require the -d directory option,
	and any existing packages in the -d directory
	will be overwritten
	if same named files are available to download/refresh.

Examples:
	$0 -i /path/to/debian-12.8.0-amd64-netinst.iso
	$0 -i /path/to/debian-12.8.0-amd64-netinst.iso -p /path/to/mini-debian.iso
	$0 -i /path/to/debian-12.8.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2504.3
	$0 -i /path/to/debian-12.8.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2504.3 -k 6.1.0-26-amd64
	$0 -i /path/to/debian-12.11.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2601.5 -k 6.1.0-35-amd64 -d /path/to/deb-files-directory
	$0 -i /path/to/debian-12.13.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2601.5 -k 6.1.0-35-amd64 -d /path/to/deb-files-directory -o /path/to/debian-12.11.0-amd64-netinst.iso
	$0 -i /path/to/debian-12.13.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2601.5 -k 6.1.0-35-amd64 -d /path/to/deb-files-directory -o /path/to/debian-12.11.0-amd64-netinst.iso -w
	$0 -i /path/to/debian-12.13.0-amd64-netinst.iso -p /path/to/mini-debian.iso -b 2601.5 -k 6.1.0-35-amd64 -d /path/to/deb-files-directory -o /path/to/debian-12.11.0-amd64-netinst.iso -w -x

You can change more options by setting Ansible variables on a per host or group basis.
This shell script is a wrapper around ansible-playbook and can run on your localhost.
Please see README.md for more information.
" 1>&2
	exit 1
}

while getopts "wxb:d:i:k:p:o:" opt; do
	case "${opt}" in
		b)
			str_script_build=${OPTARG}
			;;
		d)
			dir_deb_files=$(dir -dp ${OPTARG}) ; # add slash suffix
			;;
		i)
			fn_iso_input=${OPTARG}
			;;
		k)
			str_locked_kernel=${OPTARG}
			;;
		p)
			fn_mini_iso_input=${OPTARG}
			;;
		o)
			fn_dahdi_iso_input=${OPTARG}
			;;
		w)
			bool_download_freepbx_packages=true
			;;
		x)
			bool_refresh_packages=true
			;;
		*)
			usage
			;;
	esac
done
shift $((OPTIND-1))

if [ -z "${fn_iso_input}" ]; then
	usage
fi

extra_vars="fn_iso_input=${fn_iso_input}"

if [ -n "${fn_mini_iso_input}" ]; then
	extra_vars="${extra_vars} fn_mini_iso_input=${fn_mini_iso_input}"
fi

if [ -n "${str_script_build}" ]; then
	extra_vars="${extra_vars} str_script_build=${str_script_build}"
fi

if [ -n "${str_locked_kernel}" ]; then
	extra_vars="${extra_vars} str_locked_kernel=${str_locked_kernel}"
fi

if [ -n "${dir_deb_files}" ]; then
	extra_vars="${extra_vars} dir_deb_files=${dir_deb_files}"
fi

if [ -n "${bool_refresh_packages}" ]; then
	extra_vars="${extra_vars} bool_refresh_packages=${bool_refresh_packages}"
fi

if [ -n "${bool_download_freepbx_packages}" ]; then
	extra_vars="${extra_vars} bool_download_freepbx_packages=${bool_download_freepbx_packages}"
fi

if [ -n "${fn_dahdi_iso_input}" ]; then
	extra_vars="${extra_vars} fn_dahdi_iso_input=${fn_dahdi_iso_input}"
fi

ansible-playbook \
	--inventory localhost, \
	--connection=local \
	--extra-vars "${extra_vars}" \
	sngfdx-playbook.yml

