# SPDX-FileCopyrightText: 2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-2.0-only
---
# file: sngfdx/tasks/download.yml

- name: Download FreePBX Packages.gz file.
  ansible.builtin.get_url:
    url: "{{ preload_debfpbx_amd64_url }}/{{ item }}"
    dest: "{{ dir_deb_files }}/freepbx-packages.gz"
  loop:
    - Packages.gz

- name: Open the packages file and reverse sort the filenames.
  ansible.builtin.shell:
    cmd: zgrep "^Filename:" "{{ dir_deb_files }}/freepbx-packages.gz" | grep ".deb$" | cut -f2 -d':' | sed "s/ //g" | sort -r > "{{ dir_deb_files }}/freepbx-packages"

- name: Get the most recent of each package to download.
  ansible.builtin.shell:
    cmd: cut -f4 -d/ "{{ dir_deb_files }}/freepbx-packages" | sort -u | xargs -I '{}' grep -m 1 "/{}/" "{{ dir_deb_files }}/freepbx-packages"
  register: download_packages

- name: Download FreePBX supplied packages.
  ansible.builtin.get_url:
    url: "{{ preload_debfpbx_base_url }}/{{ item }}"
    dest: "{{ dir_deb_files }}"
  loop: "{{ download_packages.stdout | split('\n') }}"
