# SPDX-FileCopyrightText: 2025-2026 Sangoma US Inc.
# SPDX-License-Identifier: GPL-2.0-only
---
# file: sngfdx/tasks/main.yml

- name: Check for an existing output ISO with the same name.
  ansible.builtin.stat:
    path: "{{ fn_iso_output }}"
  register: stat_iso_output

- name: Confirm output ISO does not already exist.
  ansible.builtin.fail:
    msg: "Oops that output ISO already exists: '{{ fn_iso_output }}'"
  when: stat_iso_output.stat.exists

- name: Calculate a hash of the current files of this particular sngfd.
  ansible.builtin.shell:
    cmd: find roles/sngfdx -path ./.git -prune -o -follow -type f -exec sha256sum {} + | sort | sha256sum | cut -f1 -d' '
  register: sngfdx_sha256

- name: Place the stdout hash into a string.
  ansible.builtin.set_fact:
    str_sngfdx_sha256: "{{ sngfdx_sha256.stdout }}"

- name: Make temporary directories and possibly one stickier directory for downloads.
  ansible.builtin.include_tasks:
    file: directories.yml

- name: Download FreePBX packages for preloading.
  when: bool_download_freepbx_packages | bool
  ansible.builtin.include_tasks:
    file: download.yml

- name: Extract from input ISO.
  ansible.builtin.include_tasks:
    file: extract.yml

- name: Bootloader menus.
  ansible.builtin.include_tasks:
    file: bootloader.yml

- name: Preseeds for automatically answering installation questions.
  ansible.builtin.include_tasks:
    file: preseeds.yml

- name: Commands to run during preseed - boot, early, before partitioning, and late.
  ansible.builtin.include_tasks:
    file: commands.yml

- name: Special helpers.
  ansible.builtin.include_tasks:
    file: helpers.yml

- name: Output the new ISO.
  ansible.builtin.include_tasks:
    file: output.yml

- name: Generate PXE boot setup for Cobbler.
  when: fn_mini_iso_input != ""
  ansible.builtin.include_tasks:
    file: pxecob.yml

#- name: test
#  ansible.builtin.debug:
#    msg: "testing"

